name: Trigger Target Workflow

on:
  workflow_dispatch:
    inputs:
      project-name:
        description: "Please enter a project name"
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="helllth" 
          repo_name="carma"  
          event_type="trigger-workflow" 
          versionManipulator=undefined
          projectName="${{ github.event.inputs.project-name }}"
          actor="${{ github.actor }}"
          target="dev"

          echo             https://api.github.com/repos/$repo_owner/$repo_name/dispatches 


          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CISMET_CI_DEPLOY2_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\", 
                 \"client_payload\": {\"project-name\": \"$projectName\",
                                      \"target\": \"$target\", 
                                      \"version-manipulator\": $versionManipulator, 
                                      \"actor\": \"$actor\", 
                                      \"unit\": false, 
                                      \"integration\": true}}"