name: Release Action
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Versionsmanipulation im Collab-Projekt (eine der folgenden): patch, minor, major, prepatch, preminor, premajor, prerelease"
        required: true
      project-name:
        description: "Bitte geben Sie einen Projektnamen ein oder * für alle Projekte"
        required: true
      target:
        type: choice
        description: "Wohin soll ich deployen?"
        options:
          - dev
          - live
      i-know-what-im-doing:
        type: boolean
        description: "Ich weiß, was ich tue"
        required: true
      i-know-what-im-doing-multiple:
        type: boolean
        description: "Ich weiß, was ich tue, wenn ich mehrere Deployments anfordere"
        required: false
      i-know-what-im-doing-live:
        type: boolean
        description: "Ich weiß, was ich tue, wenn ich live-Deployments mache"
        required: true
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="helllth"
          repo_name="carma"
          event_type="trigger-workflow"
          versionManipulator=""
          projectName="${{ github.event.inputs['project-name'] }}"
          actor="${{ github.actor }}"
          target="dev"

          # Dynamically construct the client_payload as a single line
          if [ -z "$versionManipulator" ]; then
            payload="{\"event_type\": \"$event_type\", \"client_payload\": {\"project-name\": \"$projectName\", \"target\": \"$target\", \"actor\": \"$actor\", \"unit\": false, \"integration\": true}}"
          else
            payload="{\"event_type\": \"$event_type\", \"client_payload\": {\"project-name\": \"$projectName\", \"target\": \"$target\", \"version-manipulator\": \"$versionManipulator\", \"actor\": \"$actor\", \"unit\": false, \"integration\": true}}"
          fi

          # Print the payload (optional, for debugging purposes)
          echo "Payload: $payload"

          # Send the request
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.CISMET_CI_DEPLOY2_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "$payload"